#FROM arm64v8/alpine
FROM alpine:3.20.1
WORKDIR /root
# Upgrading system
RUN apk update
RUN apk upgrade

# Installing useful programs
RUN apk add --upgrade nano

#Get website project from github
RUN apk add --upgrade git
#RUN git clone https://github.com/yohrannes/website-portifolio.git

# Installing python, flask, uwsgi
ENV PYTHONUNBUFFERED=1
RUN apk add --update python3 py3-pip build-base python3-dev uwsgi uwsgi-python3
RUN apk add --update uwsgi-python
RUN apk add --upgrade python3 py3-pip

RUN ln -sf python3 /usr/bin/python

RUN apk add py3-flask py3-requests
RUN set FLASK_ENV=development
EXPOSE 9090

# Config crond and app
ADD crontab.txt /crontab.txt
ADD script.sh /script.sh
COPY entry.sh /entry.sh
RUN chmod 755 /script.sh /entry.sh
RUN /usr/bin/crontab /crontab.txt

COPY foobar.py /home/user/foobar.py
RUN chmod 755 /home/user/foobar.py

# Added user
RUN adduser -D user
USER user
WORKDIR /home/user

CMD ["/entry.sh"]
