FROM cgr.dev/chainguard/nginx:latest-dev AS dev
LABEL maintainer="yohrannes@gmail.com"

FROM cgr.dev/chainguard/nginx:latest

USER root

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 CMD ["nginx", "-t"]