{
 "title": "Atack Detector - Flask exporter",
 "tags": [
  "flask",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Http Methods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(flask_http_request_created) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests status",
   "type": "timeseries",
   "description": "Taxa de erros HTTP 5xx (pode indicar exploração de vulnerabilidades).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (status) (increase(flask_http_request_total[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Requisições para rotas suspeitas (exemplo: /wp-includes/, /xmlrpc.php, etc)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (path) (increase(flask_http_request_total[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}