---
build-instance-image:
  stage: pk-build-instance-image
  variables:
    HCP_CLIENT_ID: $PACKER_WEBPORT_CLIENT_ID
    HCP_CLIENT_SECRET: $PACKER_WEBPORT_CLIENT_SECRET
  tags:
    - oci-runner-arm
  script:
    - cd ${CI_PROJECT_DIR}/iac
    - chmod +x ./webport-cli/.sh
    - ./webport-cli/.sh pipe
    - |
      echo "Waiting for container to be ready..."
      for i in {1..30}; do
        if docker ps | grep -q cloud-cli; then
          echo "Container is running"
          break
        fi
        echo "Waiting... ($i/30)"
        sleep 2
      done
    - docker ps -a --no-trunc
    - docker logs cloud-cli || true
    - |
      docker exec -w /app \
        -e HCP_CLIENT_SECRET="${PACKER_WEBPORT_CLIENT_SECRET}" \
        -e HCP_CLIENT_ID="${PACKER_WEBPORT_CLIENT_ID}" \
        cloud-cli sh -c "
          cd packer/prod
          chmod +x wrapper.sh
          ./wrapper.sh
          packer build .
        "