---
build-instance-image:
  stage: pk-build-instance-image
  variables:
    HCP_CLIENT_ID: $PACKER_WEBPORT_CLIENT_ID
    HCP_CLIENT_SECRET: $PACKER_WEBPORT_CLIENT_SECRET
    TF_CLOUD_TOKEN: $TF_CLOUD_TOKEN
  tags:
    - oci-runner-arm
  before_script:
    - mkdir -p $HOME/.oci
    - echo "$OCI_CONFIG_BASE64" | base64 -d > $HOME/.oci/config
    - echo "$OCI_PRIVATE_KEY_BASE64" | base64 -d > $HOME/.oci/oci_api_key.pem
    - chmod 700 $HOME/.oci
    - chmod 600 $HOME/.oci/oci_api_key.pem
    - chmod 600 $HOME/.oci/config
    - export TF_VAR_compartment_id=$OCI_COMPARTMENT_OCID
    - export TF_VAR_region=$OCI_REGION
  script:
    - cd ${CI_PROJECT_DIR}/iac
    - chmod +x ./webport-cli/.sh
    - ./webport-cli/.sh pipe
    - |
      echo "Waiting for container to be ready..."
      for i in {1..30}; do
        if docker ps | grep -q cloud-cli; then
          echo "Container is running"
          break
        fi
        echo "Waiting... ($i/30)"
        sleep 2
      done
    - docker ps -a --no-trunc
    - docker logs cloud-cli || true
    - |
      docker exec -w /app \
        -e TF_IN_AUTOMATION=1 \
        -e TF_TOKEN_app_terraform_io="${TF_CLOUD_TOKEN}" \
        -e TF_WORKSPACE="${TF_WORKSPACE}" \
        -e HCP_CLIENT_SECRET="${PACKER_WEBPORT_CLIENT_SECRET}" \
        -e HCP_CLIENT_ID="${PACKER_WEBPORT_CLIENT_ID}" \
        cloud-cli sh -c "
          /root/init-all.sh
          pwd
          cd terraform/prod/
          pwd
          export PATH=$PATH:/app/packer/prod/ansible/venv/bin
          cd ../../packer/prod/
          ./wrapper.sh
          pwd
          env
          packer build .
        "

#delete-older-images: # New task, verify modules/packer/image-deletion.tf