---
build-instance-image:
  stage: pk-build-instance-image
  tags:
    - oci-runner-arm
  script:
    - cd ${CI_PROJECT_DIR}/iac
    - chmod +x ./webport-cli/.sh
    - ./webport-cli/.sh pipe
    - docker exec -w /app cloud-cli sh -c "
      cd packer/prod
      chmod +x wrapper.sh
      ./wrapper.sh
      packer build .
      export HCP_CLIENT_SECRET=${PACKER_WEBPORT_CLIENT_SECRET}
      export HCP_CLIENT_ID=${PACKER_WEBPORT_CLIENT_ID}
      "