---
build-instance-image:
  stage: pk-build-instance-image
  variables:
    HCP_CLIENT_ID: $PACKER_WEBPORT_CLIENT_ID
    HCP_CLIENT_SECRET: $PACKER_WEBPORT_CLIENT_SECRET
  tags:
    - oci-runner-arm
  script:
    - cd ${CI_PROJECT_DIR}/iac
    - chmod +x ./webport-cli/.sh
    - ./webport-cli/.sh pipe
    - |
      docker ps -a
      docker exec -w /app \
        -e HCP_CLIENT_SECRET=${PACKER_WEBPORT_CLIENT_SECRET} \
        -e HCP_CLIENT_ID=${PACKER_WEBPORT_CLIENT_ID} \
        cloud-cli sh -c "
          cd packer/prod
          chmod +x wrapper.sh
          ./wrapper.sh
          packer build .
        "