---
variables:
  TZ: "America/Sao_Paulo"
  TF_CLOUD_ORG: "org-website-portifolio"
  TF_CLOUD_API: "https://app.terraform.io/api/v2"
  MAX_RETRIES: 9
  RETRY_DELAY: 10
  PLAN_TIMEOUT: 1800
  APPLY_TIMEOUT: 3600
  # Fine-tuned variables for apply trigger retries
  APPLY_TRIGGER_MAX_ATTEMPTS: 90
  APPLY_TRIGGER_RETRY_DELAY: 5
  TF_ROOT: ${CI_PROJECT_DIR}/iac/terraform/prod
  TF_CONFIG_FILE: "terraform-config.tar.gz"

include:
### OCI AND CLUSTER AUTHENTICATION

  - local: 'pipelines/gitlab-ci-cd/cloud-auth/oci-oke-auth.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "main"

### GITLAB RUNNERS CONTROLER AND SETUP

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner-controler.yml'

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner1.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-runner1"

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-runner2"

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner3.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-runner3"

  - local: 'pipelines/gitlab-ci-cd/exploration.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "exploration/oke-capabilities"

### WEBAPP INFRASTRUCTURE

  - local: 'pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-webapp-failover"

  - local: 'pipelines/gitlab-ci-cd/infra-webapp/k8s-cluster/oci-oke-aways-free.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-webapp"

#  - local: 'pipelines/gitlab-ci-cd/packer/build-instance-image.yml'
#    rules:
#      - if: $CI_COMMIT_BRANCH == "infra-webapp-oci-amd-packer"

## PROD PIPELINES

  - local: 'pipelines/gitlab-ci-cd/prod.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "main"

## DEVELOPMENT PIPELINES

  - local: 'pipelines/gitlab-ci-cd/dev.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "dev"

## DOCKER IMAGES PIPELINES

  - local: 'pipelines/gitlab-ci-cd/docker-registry.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "docker-registry"


stages:
## Runner Preparation Steps
  - runner-prepare

## Packer (HCP Cloud) Steps
  - pk-build-instance-image

## Terraform (HCP Cloud) Steps
  - tf-run
  - tf-apply

  - check-infra
  - deploy-webapp

## Development pipeline Steps, to be used for Devs (main, develop).
  - check
  - build
  - test
  - pre-deploy
  - deploy-image
  - deploy


