test_job:
  stage: test  # Assuming the job is named "test"
  script:
    - echo "Current working directory: $PWD"
    - echo "Available environment variables:"
    - env
    - kubectl version  # Check if kubectl is available
    # Add specific test commands relevant to your scenario
  tags:
    - oke-yohapp-runner
