image: docker.io/library/alpine:latest

stages:
  - build

build:
  stage: build
  script:
    - echo "Building application..."
    - # Your application build commands here
    - echo "Build completed successfully!"
