stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - sudo echo "Building the ServiceAccount project..."

deploy_job:
  stage: deploy
  script:
    - sudo echo "Deploying nginx pod to the OKE cluster"
    - sudo kubectl run nginx --image=nginx
