---
variables:
  TZ: "America/Sao_Paulo"
  TF_CLOUD_ORG: "org-website-portifolio"
  TF_CLOUD_API: "https://app.terraform.io/api/v2"
  MAX_RETRIES: 9
  RETRY_DELAY: 10
  PLAN_TIMEOUT: 1800
  APPLY_TIMEOUT: 3600
  # Fine-tuned variables for apply trigger retries
  APPLY_TRIGGER_MAX_ATTEMPTS: 90
  APPLY_TRIGGER_RETRY_DELAY: 5
  TF_ROOT: ${CI_PROJECT_DIR}/iac/terraform/prod
  TF_CONFIG_FILE: "terraform-config.tar.gz"

include:
### OCI AND CLUSTER AUTHENTICATION

  - local: 'pipelines/gitlab-ci-cd/cloud-auth/oci-oke-auth.yml'

### GITLAB RUNNERS CONTROLER AND SETUP

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner-controler.yml'

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner1.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-runner1"

  - local: 'pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-runner2"

### WEBAPP INFRASTRUCTURE

  - local: 'pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-webapp-failover"

  - local: 'pipelines/gitlab-ci-cd/infra-webapp/k8s-cluster/oci-oke-aways-free.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "infra-webapp"

#  - local: 'pipelines/gitlab-ci-cd/packer/build-instance-image.yml'
#    rules:
#      - if: $CI_COMMIT_BRANCH == "infra-webapp-oci-amd-packer"

## DEVELOPMENT PIPELINES

  - local: 'pipelines/gitlab-ci-cd/develop.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "dev"

## DOCKER IMAGES PIPELINES

  - local: 'pipelines/gitlab-ci-cd/docker-registry.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "docker-registry"


stages:
## Runner Preparation Steps
  - runner-prepare

## Packer (HCP Cloud) Steps
  - pk-build-instance-image

## Terraform (HCP Cloud) Steps
  - tf-run
  - tf-apply

  - check-infra
  - deploy-webapp

## Development pipeline Steps, to be used for Devs (main, develop).
  - check
  - build
  - test
  - pre-deploy
  - deploy-image
  - deploy

deploy-dkcmpose:
  tags:
    - runner1
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_WEBAPP_FAILOVER_IP "
        mkdir -p repos-git
        cd repos-git
        git clone https://gitlab.com/yohrannes/website-portifolio.git
        cd website-portifolio
        git checkout main
        git pull origin main
        cd docker-compose
        sudo docker compose down
        sudo docker system prune -a -f
      "
  script:
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_WEBAPP_FAILOVER_IP "
        sudo docker compose -f repos-git/website-portifolio/docker-compose/docker-compose.yml up -d
      "

deploy-k8s-cluster:
  tags:
    - runner2
  stage: deploy
  extends: .oci-oke-auth
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd ${CI_PROJECT_DIR}
    - kubectl apply -f kubernetes/gateway
    - |
      helm repo add jetstack https://charts.jetstack.io
      helm repo update
      
      helm upgrade --install cert-manager jetstack/cert-manager \
        --namespace cert-manager \
        --create-namespace \
        --version 1.19.2 \
        --set config.apiVersion="controller.config.cert-manager.io/v1alpha1" \
        --set config.kind="ControllerConfiguration" \
        --set config.enableGatewayAPI=true \
        --set crds.enabled=true

    - kubectl apply -f kubernetes/cert-manager
    - kubectl apply -f kubernetes/app-manifest