job1:
  script: echo "hi there"
  image: arm64v8/docker
  services:
    - arm64v8/docker:24.0.5-dind
  before_script:
    - docker info
  resources:
    requests:
      cpu: 0.10
      memory: 200mi
    limits:
      cpu: 0.30
      memory: 300mi
