gitlabUrl: https://gitlab.com
runnerRegistrationToken: "glrt-his1ZAtmT3t9xb-fbo-Z"

runners:
  # runner configuration, where the multi line string is evaluated as a
  # template so you can specify helm values inside of it.
  #
  # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
  # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
  config: |
    [[runners]]
      name = "gitlab-runner"
      executor="kubernetes"
      environment = [
        "FF_KUBERNETES_HONOR_ENTRYPOINT=false",
        "FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=true",
        ]
      [runners.kubernetes]
        networkMode = "host"
        poll_timeout = 2000
        node_selector_overwrite_allowed = ".*"
        helper_image = "docker.io/docker:19.03.8-dind"
        namespace = "{{.Release.Namespace}}"
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]

unregisterRunners: true

securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  privileged: true
  capabilities:
    drop: ["ALL"]
