apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webport-cert
  namespace: website-portifolio
spec:
  secretName: webport-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - k8s.yohrannes.com