---
include:
  - local: 'pipelines/gitlab-ci-cd/terraform/trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/apply.yml'

variables:
  TF_WORKSPACE: "webapp_prod"
  TF_TARGET_ADDRS: 'module.webapp'

trigger-terraform-run:
  when: manual
  stage: tf-run
  extends:
    - .trigger-terraform-run

terraform-apply:
  when: manual
  stage: tf-apply
  extends: .terraform-apply
  needs:
    - trigger-terraform-run

autenticate-oci:
  stage: check-infra
  tags:
    - runner1
  before_script:
    - docker pull ghcr.io/oracle/oci-cli:latest
    - docker tag ghcr.io/oracle/oci-cli:latest oci
    - export OCI_CONFIG="$OCI_CONFIG_BASE64"
    - export OCI_PRIVATE_KEY="$OCI_PRIVATE_KEY_BASE64"

  script:
    - |
      alias oci='docker run --rm -it \
        -e OCI_CONFIG=$OCI_CONFIG \
        -e OCI_PRIVATE_KEY=$OCI_PRIVATE_KEY \
        oci \
        -c "mkdir -p ~/.oci && \
            echo \"\$OCI_CONFIG\" > ~/.oci/config && \
            echo \"\$OCI_PRIVATE_KEY\" > ~/.oci/oci_api_key.pem && \
            chmod 600 ~/.oci/oci_api_key.pem && \
            exec oci"'
      oci --version
      oci iam region list

#install-gateway:
#  tags:
#    - runner1
#  when: manual
#  needs:
#    - autenticate-oci
#  stage: create-infra
#  script:
#    - |
#      kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.6.2" | kubectl apply -f -
#      kubectl apply -f https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/crds.yaml
#      kubectl apply -f https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/default/deploy.yaml


#set-lb-shape: # This job doesn't works imediately after the cluster creation, it needs to be run manually. Implement a check to ensure the load balancer is ready to be updated.
#  needs:
#    - install-gateway
#  stage: create-infra
#  script:
#    - |
#      export COMPARTMENT_ID=$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/"//g')
#      export LOAD_BALANCER_ID=$(oci lb load-balancer list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/"//g')
#      OUTPUT=\$(oci lb load-balancer update-load-balancer-shape --load-balancer-id $LOAD_BALANCER_ID --shape-name flexible --shape-details '{"maximum-bandwidth-in-mbps":10,"minimum-bandwidth-in-mbps":10}' --force 2>&1)
#      EXIT_CODE=$?
#      if [ $EXIT_CODE -ne 0 ] && echo "$OUTPUT" | grep -q 'same values'; then
#          echo "No changes made, the load balancer is already using the specified shape and bandwidth."
#          exit 0
#      elif [ $EXIT_CODE -ne 0 ]; then
#          echo "$OUTPUT"
#          exit 1
#      fi


### Verify Load Balancer (not network load balancer) destruction on terraform...
---