---
include:
  - local: 'pipelines/gitlab-ci-cd/terraform/trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/apply.yml'

variables:
  TF_WORKSPACE: "webapp_prod"
  TF_TARGET_ADDRS: 'module.webapp'

trigger-terraform-run:
  stage: tf-run
  extends:
    - .trigger-terraform-run

terraform-apply:
  stage: tf-apply
  extends: .terraform-apply
  needs:
    - trigger-terraform-run

get-instance-ip:
  stage: check-infra
  script:
    - |
      WORKSPACE_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_CLOUD_WORKSPACE" \
        | jq -r '.data[0].id')

    - |
      STATE_VERSION_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_CLOUD_WORKSPACE" \
        | jq -r '.data[0].relationships["current-state-version"].data.id')
    
#    - |
#      INSTANCE_PUBLIC_IP=$(curl -s \
#        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
#        --header "Content-Type: application/vnd.api+json" \
#        "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
#        | jq -r '.data[] | select(.attributes.name == "webapp_pub_ip") | .attributes.value')
#      if [ -z "$INSTANCE_PUBLIC_IP" ] || [ "$INSTANCE_PUBLIC_IP" = "null" ]; then
#        echo "ERROR: Failed to extract IP address"
#        exit 1
#      fi
    
#    - |
#      RESPONSE=$(curl -s --write-out "\n%{http_code}" \
#        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
#        --request PUT \
#        --form "value=$INSTANCE_PUBLIC_IP" \
#        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_WEBAPP_IP") >  /dev/null 2>&1
#      
#      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
#      echo "HTTP Status: $HTTP_CODE"
#      
#      if [ "$HTTP_CODE" != "200" ]; then
#        echo "ERROR: Failed to update GitLab variable"
#        exit 1
#      fi

install-kubectl:
  tags: [ "runner1" ]
  when: manual
  needs:
    - create-oci-oke-cluster
  stage: create-infra
  script:
    - |
        export STABLE_RELEASE=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -LO https://dl.k8s.io/release/\$STABLE_RELEASE/bin/linux/arm64/kubectl
        chmod +x kubectl
        mv kubectl /usr/local/bin/kubectl
        /usr/local/bin/kubectl version --client
        export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/\"//g')
        export CLUSTER_ID=\$(oci ce cluster list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/\"//g')
        terraform state rm module.oci_oke_cluster_arm.module.kubeconfig.null_resource.create_kubeconfig
        terraform plan -out plan -detailed-exitcode --target=module.oci_oke_cluster_arm.module.kubeconfig -out=plan 2>&1 | grep -o -E 'oci[^.]*.' | sort -u
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$KUBECONFIG_CONTENT" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/OCI_KUBECONFIG_CONTENT"

install-gateway:
  tags: [ "runner1" ]
  when: manual
  needs:
    - install-kubectl
  stage: create-infra
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        kubectl kustomize "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.6.2" | kubectl apply -f -
        kubectl apply -f https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/crds.yaml
        kubectl apply -f https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/default/deploy.yaml
      "


set-lb-shape: # This job doesn't works imediately after the cluster creation, it needs to be run manually. Implement a check to ensure the load balancer is ready to be updated.
  tags: [ "runner1" ]
  when: manual
  needs:
    - install-gateway
  stage: create-infra
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/\"//g')
        export LOAD_BALANCER_ID=\$(oci lb load-balancer list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/\"//g')
        OUTPUT=\$(oci lb load-balancer update-load-balancer-shape --load-balancer-id \$LOAD_BALANCER_ID --shape-name flexible --shape-details '{\"maximum-bandwidth-in-mbps\":10,\"minimum-bandwidth-in-mbps\":10}' --force 2>&1)
        EXIT_CODE=\$?
        if [ \$EXIT_CODE -ne 0 ] && echo \"\$OUTPUT\" | grep -q 'same values'; then
            echo \"No changes made, the load balancer is already using the specified shape and bandwidth.\"
            exit 0
        elif [ \$EXIT_CODE -ne 0 ]; then
            echo \"\$OUTPUT\"
            exit 1
        fi
      "


### Verify Load Balancer (not network load balancer) destruction on terraform