clean-docker-engine:
  stage: prepare
#  rules:
#      - if: $CI_COMMIT_BRANCH == "develop"

  # Run in 2 runners simultaneously
  parallel: 2

  image: docker:27.3.1
  services:
   - docker:27.3.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker system prune -a -f