runner1-docker-prune:
  stage: runner-prepare
  tags:
    - runner1
  when: manual
  allow_failure: true
  script:
    - docker volume prune -af
    - docker system prune -af
 
runner2-docker-prune:
  stage: runner-prepare
  tags:
    - runner2
  when: manual
  allow_failure: true
  script:
    - docker volume prune -af
    - docker system prune -af