runner1-controler:
  stage: runner-prepare
  tags:
    - runner1
  when: manual
  allow_failure: true
  script:
    - sudo docker volume prune -af
    - sudo docker system prune -af
 
runner2-controler:
  stage: runner-prepare
  tags:
    - runner2
  when: manual
  allow_failure: true
  script:
    - sudo docker volume prune -af
    - sudo docker system prune -af