gitlabUrl: https://gitlab.com

runners:
  # runner configuration, where the multi line string is evaluated as a
  # template so you can specify helm values inside of it.
  #
  # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
  # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html


  config: |
    [[runners]]
      name = "gitlab-runner"
      executor="kubernetes"
      environment = [
        "FF_KUBERNETES_HONOR_ENTRYPOINT=false",
        "FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=true",
        ]
      [runners.kubernetes]
        pull_policy = "always"
        networkMode = "host"
        privileged = true
        tls_verify = false
        image = "arm64v8/docker:dind"
        helper_image = "gitlab/gitlab-runner-helper:ubuntu-arm64-v14.10.2"
        namespace = "{{.Release.Namespace}}"
      [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
  image_pull_policy: "Always"
  secret: gitlab-runner-secret

securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  privileged: true
