apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
data:
  runner-registration-token: "" # need to leave as an empty string for compatibility reasons
  runner-token: "Z2xydC15WnpLOEsyVUhMa0pWLXdoemFUcwo=" # echo "glrt-yZzK8K2UHLkJV-whzaTs" | base64
