apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: "" # need to leave as an empty string for compatibility reasons
  runner-token: "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsSlJVMTlEUW5NMGNVNHRhbUY2Y210TlJUQm5iRmN6UjBKRlNIbHBNRGd6U0hkV09HNW1WekZ5VkVFaWZRLmV5SmhkV1FpT2xzaVlYQnBJbDBzSW1W
NGNDSTZNVGN4T1RjMk1EVXdPU3dpYVdGMElqb3hOekU1TnpVMk9UQTVMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwydDFZbVZ5Ym1WMFpYTXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJDSXNJ
bXQxWW1WeWJtVjBaWE11YVc4aU9uc2libUZ0WlhOd1lXTmxJam9pYTNWaVpTMXplWE4wWlcwaUxDSnpaWEoyYVdObFlXTmpiM1Z1ZENJNmV5SnVZVzFsSWpvaWEySmpiMjVtYVdjdFoybDBiR0ZpTFhO
aElpd2lkV2xrSWpvaVltUmtOekE0TURFdFpXUmlaQzAwT1RObExXRTROVFV0WmpobFl6ZG1OV0l5TlRrMUluMTlMQ0p1WW1ZaU9qRTNNVGszTlRZNU1Ea3NJbk4xWWlJNkluTjVjM1JsYlRwelpYSjJh
V05sWVdOamIzVnVkRHByZFdKbExYTjVjM1JsYlRwclltTnZibVpwWnkxbmFYUnNZV0l0YzJFaWZRLnQ5SC1EeW5YRXlTMEhRYURpTVlLT1NrNlFjN0MxYjZ6LUhSODA0T3E2LTdkem1nRElVRndlYlNy
VktVSHliQmJwVTVMZnVTRE92cHByQl9kTlBfMHFPZ3dyTjJLby1VLUVRalJQaXVRT0lLY0F5UHl3ekRBTUlWTWowM3J3WXpvdFI3ZGZBVTNjM0tlQ1hROEh1c1doR2dlRUNHOXJabkpRSFIzcll0R0FF
V3BPRDVEN3ZuUDFnVmpnSXgyajBoWklGaFZaQUo4SXV6TERtVUd2ZjhIbms2ZVhUUGNuQUMwMVkwNHIwOF9NR1FhcllLX2hvOTJGNDI3LUUzWDVQLVZxWkppaHNFaEpkUW1CQk1xeDd0Q25tdF95di1m
RmM4RW83Y1Y1Ni1CNUFSZ1dub3NoMGtrOFBrZXEwckVMUGdNWDZ3WGU1RnBTbGNqVjdzeFlKc0RfQQo="
