---
multi-cloud-auth:
  tags: [ "oci-runner-arm" ]
  stage: prepare
  script:
    # Autencicate with OCI
    - mkdir -p $HOME/.oci
    - echo "$OCI_CONFIG_BASE64" | base64 -d > $HOME/.oci/config
    - echo "$OCI_PRIVATE_KEY_BASE64" | base64 -d > $HOME/.oci/oci_api_key.pem
    - chmod 700 $HOME/.oci
    - chmod 600 $HOME/.oci/oci_api_key.pem
    - chmod 600 $HOME/.oci/config
    - export TF_VAR_compartment_id=$OCI_COMPARTMENT_OCID
    - export TF_VAR_region=$OCI_REGION

    # Autencicate with AWS
    - mkdir -p $HOME/.aws
    - echo "$AWS_CONFIG_BASE64" | base64 -d > $HOME/.aws/config
    - echo "$AWS_CREDENTIALS_BASE64" | base64 -d > $HOME/.aws/credentials
    - chmod 700 $HOME/.aws
    - chmod 600 $HOME/.aws/credentials
    - chmod 600 $HOME/.aws/config

    # Prepare SSH files to enable ssh conection with instance
    - sudo apt-get install -y openssh-client openssh-server curl
    - mkdir -p $HOME/.ssh
    - (echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > $HOME/.ssh/id_rsa 2>/dev/null)
    - (echo "$SSH_PUBLIC_KEY_BASE64" | base64 -d > $HOME/.ssh/id_rsa.pub 2>/dev/null)
    - chmod 644 $HOME/.ssh/id_rsa.pub

run-terraform-container:
  tags: [ "oci-runner-arm" ]
  needs:
    - multi-cloud-auth
  stage: prepare
  before_script:
    # Build terraform container for runner host architecture (auto-detected)
    - |
      ARCH=$(uname -m)
      case $ARCH in
        "x86_64") PLATFORM="linux/amd64" ;;
        "aarch64") PLATFORM="linux/arm64" ;;
        *) echo "Arch not suported: $ARCH"; exit 1 ;;
      esac 2>/dev/null

      docker buildx build  -f ./build-tf-multi-arch/Dockerfile \
        --platform $PLATFORM \
        -t yohrannes/terraform:latest \
        --build-arg PRODUCT=terraform \
        --build-arg VERSION=1.11.0 \
        --load . 2>/dev/null

    # Check old terraform containers and remove them
    - |
      if [ "$(docker ps -a -q -f name=^terraform-container$)" ]; then
        echo "Old terraform container found removing..."
        docker stop terraform-container
        docker rm terraform-container
      fi

  script:
    # Prepare and run terraform-container
    - |
      docker run -d --name terraform-container \
      --entrypoint "" hashicorp/terraform:latest sleep 3600
    - docker cp $CI_PROJECT_DIR/terraform/prod terraform-container:/app > /dev/null 2>&1
    - echo $CI_PROJECT_DIR/terraform/prod
    - docker cp $HOME/.oci terraform-container:/root/.oci
    - docker cp $HOME/.aws terraform-container:/root/.aws > /dev/null 2>&1
    - docker exec -w /app terraform-container mkdir /root/.ssh > /dev/null 2>&1
    - docker cp $HOME/.ssh/id_rsa.pub terraform-container:/root/.ssh/id_rsa.pub > /dev/null 2>&1

create-oci-oke-cluster:
  tags: [ "oci-runner-arm" ]
  needs:
      - run-terraform-container
  stage: create-infra
  before_script:
    - |
      docker exec -w /app terraform-container sh -c "
        terraform init -reconfigure 2>/dev/null
        terraform workspace select oci_oke_web_port_prod 2>/dev/null
        terraform plan -detailed-exitcode -target=module.oci_oke_cluster_arm -out=plan | grep -o -E 'module.oci_oke_cluster_arm[^.]*.'
        apk add oci-cli curl jq --no-cache
      " 2>/dev/null
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        terraform apply plan | grep -o -E 'oci[^.]*.'
        exit_code=${PIPESTATUS[0]}
        echo "Exit Code: $exit_code"
        exit $exit_code
      " 2>/dev/null

install-kubectl:
  tags: [ "oci-runner-arm" ]
  needs:
    - create-oci-oke-cluster
  stage: create-infra
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        export STABLE_RELEASE=\$(curl -L -s https://dl.k8s.io/release/stable.txt);
        echo \$STABLE_RELEASE;
        curl -LO \"https://dl.k8s.io/release/\$STABLE_RELEASE/bin/linux/amd64/kubectl\";
        echo \"https://dl.k8s.io/release/\$STABLE_RELEASE/bin/linux/amd64/kubectl\";
        curl -LO \"https://dl.k8s.io/release/\$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        echo "$?"
        chmod +x kubectl;
        ls -la
        mv kubectl /usr/local/bin/
        echo "$?"
        kubectl version --client
      "

install-gateway-api:
  tags: [ "oci-runner-arm" ]
  needs:
    - install-kubectl
  stage: create-infra
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
      "

update-load-balancer-shape:
  tags: [ "oci-runner-arm" ]
  needs:
    - install-gateway-api
  stage: create-infra
  script:
    - |
      docker exec -w /app terraform-container sh -c "
        export COMPARTMENT_ID=$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/"//g')
        export LOAD_BALANCER_ID=$(oci lb load-balancer list --compartment-id $COMPARTMENT_ID | jq '.data[0].id' | sed 's/"//g')
        yes | oci lb load-balancer update-load-balancer-shape --load-balancer-id $LOAD_BALANCER_ID --shape-name flexible --shape-details '{\"maximum-bandwidth-in-mbps\": 10,\"minimum-bandwidth-in-mbps\": 10}'
      "
