deploy-app-dkcmpose:
  tags:
    - runner1
  stage: deploy
  when: manual
  before_script:
    - |
      set +x
      mkdir -p ~/.ssh
      echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_WEBAPP_FAILOVER_IP "
        sudo rm -rf repos-git
        mkdir -p repos-git && cd repos-git
        if [ ! -d website-portifolio ]; then
          git clone --recurse-submodules https://gitlab.com/yohrannes/website-portifolio.git
        fi
        cd website-portifolio
        git checkout main && git pull origin main
        curl -L https://github.com/yohrannes/yohrannes.com/archive/refs/heads/main.tar.gz | tar -xz --strip-components=1 "yohrannes.com-main/docker-compose"

        sudo docker ps -aq | xargs -r sudo docker rm -f
        sudo docker system prune -af
      "

### fail2ban env variables - task - turn all variables in just one .env file, modularizing env variables.
#        export F2B_HTTP_INJ_FILTER_B64=${F2B_HTTP_INJ_FILTER_B64}
#        export COMPOSE_BAKE=true
#        export MY_UID=$(id -u)
#        export MY_GID=$(id -g)
#
#        touch /tmp/export.txt
#
#        echo ${F2B_HTTP_INJ_FILTER_B64} >> /tmp/export.txt
#        echo >> /tmp/export.txt
#        echo ${MY_UID} >> /tmp/export.txt
#        echo >> /tmp/export.txt
#        echo ${MY_GID} >> /tmp/export.txt
#        echo >> /tmp/export.txt
#        echo ${COMPOSE_BAKE} >> /tmp/export.txt
#        
#        if [ -n \"\$F2B_HTTP_INJ_FILTER_B64\" ]; then
#          export F2B_HTTP_INJ_FILTER_DECODED=\"\$(echo \$F2B_HTTP_INJ_FILTER_B64 | base64 --decode)\"
#        fi
#
#        echo ${F2B_HTTP_INJ_FILTER_DECODED} >> /tmp/export.txt

  script:
    - |
      set +x
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_WEBAPP_FAILOVER_IP '
        cd repos-git/website-portifolio/docker-compose
        sudo docker compose up -d --quiet-pull
      '

deploy-app-k8s-cluster:
  tags:
    - runner1
  when: manual
  stage: deploy
  script:
    - |
      set +x
      cd ${CI_PROJECT_DIR}
      curl -L https://github.com/yohrannes/yohrannes.com/archive/refs/heads/main.tar.gz | tar -xz --strip-components=1 "yohrannes.com-main/kubernetes"
      kubectl apply -f kubernetes/nginx-gateway-fabric
      kubectl apply -k kubernetes/app-manifest
      