runner-controler-start:
  stage: prepare
  # Run in jobs in all runners simultaneously
#  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
  tags:
    - oci-runner-arm
  script:
    - docker rm -f $(docker ps -aq)
    - docker volume rm $(docker volume ls -q)
    - docker system prune -af

runner-controler-stop:
  stage: check-infra
  # Run in jobs in all runners simultaneously
#  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
  tags:
    - oci-runner-arm
  script:
    - docker rm -f $(docker ps -aq)
    - docker volume rm $(docker volume ls -q)
    - docker system prune -af
    - systemctl restart gitlab-runner