runner-controler-start:
  stage: prepare
  # Run in jobs in all runners simultaneously
#  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
      - if: $CI_COMMIT_BRANCH != "dev-dk-img"
  tags:
    - oci-runner-arm
  script:
    - docker system prune -af
    - docker volume prune -f
    - |
      if [ "$(docker ps -aq -f name=terraform-container)" ]; then
        docker rm -f terraform-container || docker stop terraform-container && docker rm terraform-container
      fi
#runner-controler-stop:
#  stage: clean-runner
##########################3 needs:
  ###############  - runner-controler-start  xxxxxxxxxxxxx - all jobs finished
  # Run in jobs in all runners simultaneously
#  parallel: 2
#  rules:
#      - if: $CI_COMMIT_BRANCH != "main"
#  tags:
#    - oci-runner-arm
#  script:
#    - docker volume prune -f
#    - docker system prune -af