runner-controler-start:
  stage: runner-prepare
  # Run in jobs in all runners simultaneously
  parallel: 2
  tags:
    - oci-runner-arm
    - gcp-runner-amd
    - local-runner-amd
  script:
    - sudo docker volume prune -af
    - sudo docker system prune -af

install-dependencies:
  stage: runner-prepare
  tags:
####OBS: runner1 already has this step
    - runner2
  script:
    - apt-get install -y curl jq tar gzip