runner-controler-start:
  stage: prepare
  # Run in jobs in all runners simultaneously
#  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
      - if: $CI_COMMIT_BRANCH != "dev-dk-img"
  tags:
    - oci-runner-arm
  script:
    - docker volume prune -f
    - docker system prune -af

runner-controler-stop:
  stage: clean-runner
  needs:
    - runner-controler-start
  # Run in jobs in all runners simultaneously
#  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
  tags:
    - oci-runner-arm
  script:
    - docker volume prune -f
    - docker system prune -af