runner-controler-start:
  stage: prepare
  # Run in jobs in all runners simultaneously
  parallel: 2
  rules:
      - if: $CI_COMMIT_BRANCH != "main"
      - if: $CI_COMMIT_BRANCH != "dev-dk-img"
  tags:
    - oci-runner-arm
  script:
    - sudo rm -rf ${CI_PROJECT_DIR}
    - docker ps -a -q | xargs -r docker stop
    - docker ps -a -q | xargs -r docker rm
    - docker volume prune -f
    - docker system prune -af

#test
#runner-controler-stop:
#  stage: clean-runner
##########################3 needs:
  ###############  - runner-controler-start  xxxxxxxxxxxxx - all jobs finished
  # Run in jobs in all runners simultaneously
#  parallel: 2
#  rules:
#      - if: $CI_COMMIT_BRANCH != "main"
#  tags:
#    - oci-runner-arm
#  script:
#    - docker volume prune -f
#    - docker system prune -af
