clean-docker-engine:
  stage: prepare
#  rules:
#      - if: $CI_COMMIT_BRANCH == "develop"

  # Run in 2 runners simultaneously
  parallel: 2
  script:
    - docker system prune -a -f
    - |
      docker run -d --name terraform-container \
      --entrypoint "" hashicorp/terraform:latest sleep 3600
    - docker cp $CI_PROJECT_DIR/terraform/prod terraform-container:/app > /dev/null 2>&1
    - ls -lahtr $CI_PROJECT_DIR/terraform/prod
    - echo $CI_PROJECT_DIR/terraform/prod
    - docker cp /root/.oci terraform-container:/root/.oci > /dev/null 2>&1