---
# First runner provision, execute this pipeline locally using gl runner type docker

variables:
  TF_WORKSPACE: "runner1_prod"
  TF_TARGET_ADDRS: 'module.runner1'

include:
  - local: 'pipelines/gitlab-ci-cd/terraform/upload-trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/monitor-apply.yml'

install-dependencies:
  stage: check-infra
  script:
    - apt-get install -y curl jq tar gzip

get-instance-ip-from-tf-cloud:
  stage: check-infra
  script:
    - |
      WORKSPACE_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_CLOUD_WORKSPACE" \
        | jq -r '.data[0].id')

    - |
      STATE_VERSION_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_CLOUD_WORKSPACE" \
        | jq -r '.data[0].relationships["current-state-version"].data.id')
    
    - |
      INSTANCE_PUBLIC_IP=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
        | jq -r '.data[] | select(.attributes.name == "runner1_pub_ip") | .attributes.value')
      
      if [ -z "$INSTANCE_PUBLIC_IP" ] || [ "$INSTANCE_PUBLIC_IP" = "null" ]; then
        echo "ERROR: Failed to extract IP address"
        exit 1
      fi
    
    - |
      RESPONSE=$(curl -s --write-out "\n%{http_code}" \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$INSTANCE_PUBLIC_IP" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_RUNNER1_IP") >  /dev/null 2>&1
      
      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
      echo "HTTP Status: $HTTP_CODE"
      
      if [ "$HTTP_CODE" != "200" ]; then
        echo "ERROR: Failed to update GitLab variable"
        exit 1
      fi

    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$INSTANCE_PUBLIC_IP" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_RUNNER1_IP"

check-startup-script:
  stage: check-infra
  needs:
    - get-instance-ip-from-tf-cloud
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      echo "Waiting for instance to be ready..."
      sleep 30
      
      MAX_ATTEMPTS=60
      ATTEMPT=0
      
      while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
        ATTEMPT=$((ATTEMPT + 1))
        echo "Attempt $ATTEMPT of $MAX_ATTEMPTS"
        
        if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -i ~/.ssh/id_rsa ubuntu@$PROD_RUNNER1_IP "
          if [ -f /var/log/startup-script.log ] && [ -r /var/log/startup-script.log ]; then
            last_line=\$(tail -n1 /var/log/startup-script.log 2>/dev/null)
            if [ \"\$last_line\" = 'startup-script-finished' ]; then
              echo 'Startup script finished successfully'
              exit 0
            else
              echo 'Still running. Last line:' \$last_line
              exit 1
            fi
          else
            echo 'Log file not available yet'
            exit 1
          fi
        "; then
          echo "Instance is ready!"
          exit 0
        fi
        
        sleep 10
      done
      
      echo "ERROR: Timeout waiting for startup script"
      exit 1

##### NOT WORKING FIXXME
delete-old-runner-gl-api:
  stage: check-infra
  before_script:
    - |
      RUNNER_ID=$(curl --request POST \
        --url "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/runners" \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_CREATOR" \
        --data "runner_type=project_type" \
        --data "project_id=$CI_PROJECT_ID" \
        --data "tag_list=runner1" | jq -r '.id')

    - echo "RUNNER_ID=$RUNNER_ID"

  script:
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
      --request DELETE \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/runners/$RUNNER_ID" \
#      > /dev/null 2>&1

create-runner-gl-api:
  stage: check-infra
  before_script:
    - |
      RUNNER_TOKEN=$(curl --request POST --url "https://gitlab.com/api/v4/user/runners" \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
        --data "runner_type=project_type" \
        --data "project_id=$CI_PROJECT_ID" \
        --data "tag_list=runner1" \
        --data "description=runner1" | jq -r '.token')
  script:
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$RUNNER_TOKEN" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/GITLAB_RUNNER_TOKEN_CREATED_OCI_ARM" \
        > /dev/null 2>&1

authorize-runner:
  stage: check-infra
  needs:
    - check-startup-script
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_RUNNER1_IP "
        sudo gitlab-runner register \
        --non-interactive \
        --url "https://gitlab.com/" \
        --token "$GITLAB_RUNNER_TOKEN_CREATED_OCI_ARM" \
        --executor "shell" \
        --description "shell-runner-with-sudo"
        sudo EDITOR='tee -a' visudo <<EOF
      gitlab-runner ALL=(ALL:ALL) ALL
      gitlab-runner ALL=(ALL) NOPASSWD: ALL
      EOF
        sudo usermod -a -G sudo gitlab-runner
        sudo usermod -aG docker gitlab-runner
        exit

      sudo tee /home/ubuntu/.gitlab-runner/config.toml > /dev/null <<'EOF'
      [[runners]]
      name = "shell-runner"
      url = "https://gitlab.com/"
      token = "$GITLAB_RUNNER_TOKEN_CREATED_OCI_ARM"
      executor = "shell"
      [runners.shell]
        tls_verify = false
        privileged = true
      EOF

      "
