---
variables:
  TF_WORKSPACE: "runner2_prod"
  TF_TARGET_ADDRS: 'module.runner2'

include:
  - local: 'pipelines/gitlab-ci-cd/terraform/trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/apply.yml'

get-instance-ip-from-tf-cloud:
  stage: check
  script:

    - |
      WORKSPACE_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_WORKSPACE" \
        | jq -r '.data.id')
    
    - |
      STATE_VERSION_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/current-state-version" \
        | jq -r '.data.id')
    
    - |
      INSTANCE_PUBLIC_IP=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
        | jq -r '.data[] | select(.attributes.name == "runner2_pub_ip") | .attributes.value')
    
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$INSTANCE_PUBLIC_IP" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_RUNNER2_IP" \
        > /dev/null 2>&1

check-startup-script:
  stage: check-infra
  needs:
    - get-instance-ip-from-tf-cloud
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      echo "Waiting for instance to be ready..."
      sleep 30
      
      MAX_ATTEMPTS=60
      ATTEMPT=0
      
      while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
        ATTEMPT=$((ATTEMPT + 1))
        echo "Attempt $ATTEMPT of $MAX_ATTEMPTS"
        
        SSH_OUTPUT=$(ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=5 -i ~/.ssh/id_rsa ubuntu@$PROD_RUNNER1_IP "
          if [ -f /var/log/startup-script.log ] && [ -r /var/log/startup-script.log ]; then
            last_line=\$(tail -n1 /var/log/startup-script.log 2>/dev/null)
            if [ \"\$last_line\" = 'startup-script-finished' ]; then
              echo 'SUCCESS'
              exit 0
            else
              echo 'RUNNING'
              exit 1
            fi
          else
            echo 'NOT_READY'
            exit 1
          fi
        " 2>&1 || true)
        
        SSH_EXIT_CODE=$?
        
        echo "SSH output: $SSH_OUTPUT"
        
        if echo "$SSH_OUTPUT" | grep -q "SUCCESS"; then
          echo "Instance is ready!"
          exit 0
        fi
        
        if echo "$SSH_OUTPUT" | grep -q "RUNNING"; then
          echo "Startup script still running"
        elif echo "$SSH_OUTPUT" | grep -q "NOT_READY"; then
          echo "Log file not available yet"
        else
          echo "Connection issue or other error, retrying..."
        fi
        
        sleep 10
      done
      
      echo "ERROR: Timeout waiting for startup script"
      exit 1

delete-old-runner-gl-api:
  stage: check-infra
  script:
    - |
      RUNNERS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/runners")
      
      RUNNER_ID=$(echo "$RUNNERS" | jq -r '.[] | select(.description == "runner2") | .id')
      
      if [ -z "$RUNNER_ID" ] || [ "$RUNNER_ID" = "null" ]; then
        echo "No runner found with description 'runner1'"
        exit 0
      fi
      
      echo "Found runner ID: $RUNNER_ID"
      
      HTTP_CODE=$(curl -s --output /dev/null --write-out "%{http_code}" \
        --request DELETE \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
        "https://gitlab.com/api/v4/runners/$RUNNER_ID")
      
      if [ "$HTTP_CODE" = "204" ] || [ "$HTTP_CODE" = "200" ]; then
        echo "Runner deleted successfully"
      else
        echo "Failed to delete runner. HTTP code: $HTTP_CODE"
        exit 1
      fi

create-runner-gl-api:
  stage: check-infra
  before_script:
    - |
      RUNNER_TOKEN=$(curl -s --request POST --url "https://gitlab.com/api/v4/user/runners" \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
        --data "runner_type=project_type" \
        --data "project_id=$CI_PROJECT_ID" \
        --data "tag_list=runner2" \
        --data "description=runner2" | jq -r '.token')
  script:
    - |
      curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$RUNNER_TOKEN" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/GITLAB_RUNNER2_TOKEN_CREATED" \
        > /dev/null 2>&1

authorize-runner:
  stage: check-infra
  needs:
    - check-startup-script
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$PROD_RUNNER1_IP "
        sudo gitlab-runner register \
        --non-interactive \
        --url "https://gitlab.com/" \
        --token "$GITLAB_RUNNER2_TOKEN_CREATED" \
        --executor "shell" \
        --description "shell-runner-with-sudo"
        sudo EDITOR='tee -a' visudo <<EOF
      gitlab-runner ALL=(ALL:ALL) ALL
      gitlab-runner ALL=(ALL) NOPASSWD: ALL
      EOF
        sudo usermod -a -G sudo gitlab-runner
        sudo usermod -aG docker gitlab-runner
        exit

      sudo tee /home/ubuntu/.gitlab-runner/config.toml > /dev/null <<'EOF'
      [[runners]]
      name = "shell-runner"
      url = "https://gitlab.com/"
      token = "$GITLAB_RUNNER2_TOKEN_CREATED"
      executor = "shell"
      [runners.shell]
        tls_verify = false
        privileged = true
      EOF

      "