.oci-oke-auth:
  stage: check-infra
  tags:
    - runner2
  before_script:
    - whoami
    - pwd
    - echo $HOME

    - export OCI_CONFIG="$(echo $OCI_CONFIG_BASE64 | base64 -d)"
    - export OCI_PRIVATE_KEY="$(echo $OCI_PRIVATE_KEY_BASE64 | base64 -d)"
    - export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True

    - mkdir -p $HOME/.oci
    - echo $OCI_CONFIG > $HOME/.oci/config
    - echo $OCI_PRIVATE_KEY > $HOME/.oci/oci_api_key.pem
    - chmod 600 $HOME/.oci/oci_api_key.pem

    - mkdir -p $HOME/.kube
    - chmod 700 $HOME/.kube
    - touch $HOME/.kube/config
    - chmod 600 $HOME/.kube/config
    - export KUBECONFIG="${HOME}/.kube/config"

    - |
      cat > $HOME/.kube/config << 'EOF'
      apiVersion: v1
      kind: Config
      clusters:
      users:
      contexts:
      EOF

# Check oci authentication
    - |
      oci iam user get \
        --user-id $(oci iam user list \
        --query "data[0].id" \
        --raw-output 2>/dev/null) --output json 2>/dev/null | jq -r .data.name > /home/gitlab-runner/oci-log.txt
 
  script:
    - |
      oci ce cluster create-kubeconfig \
        --cluster-id $PROD_WEBAPP_CLUSTER_ID \
        --file /oracle/.kube/config \
        --token-version 2.0.0 \
        --kube-endpoint PUBLIC_ENDPOINT \
        --profile DEFAULT
    - kubectl version
    - kubectl version --client
#    - k get namespaces 
#    - k get componentstatuses