---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus-pod
  name: prometheus-pod
  namespace: monit
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v3.3.1
      ports:
        - containerPort: 9090
          protocol: TCP
      resources:
        limits:
          cpu: 300m
          memory: "150Mi"
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafana-pod
  name: grafana-pod
  namespace: monit
spec:
  containers:
    - name: grafana
      image: grafana/grafana:latest
      ports:
        - containerPort: 3000
          protocol: TCP
      resources:
        limits:
          cpu: 300m
          memory: "150Mi"
  restartPolicy: OnFailure
---