---
monitor-and-apply-terraform-run:
  stage: tf-plan-apply
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
      - stuck_or_timeout_failure
  timeout: 2h
  before_script:
    - |
      if [ -z "$TF_CLOUD_TOKEN" ]; then
        echo "ERROR: TF_CLOUD_TOKEN is not set"
        exit 1
      fi
    - |
      validate_json_response() {
        local response="$1"
        local context="$2"
        if ! echo "$response" | jq . >/dev/null 2>&1; then
          echo "ERROR: Invalid JSON response from $context"
          echo "Response: $response"
          return 1
        fi
        return 0
      }
    - |
      api_call_with_retry() {
        local url="$1"
        local method="${2:-GET}"
        local data="$3"
        local max_attempts="$MAX_RETRIES"
        local attempt=1
        
        while [ $attempt -le $max_attempts ]; do
          if [ "$method" = "POST" ] && [ -n "$data" ]; then
            response=$(curl -s -w "\n%{http_code}" \
              --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
              --header "Content-Type: application/vnd.api+json" \
              --request POST \
              --data "$data" \
              "$url")
          elif [ "$method" = "POST" ]; then
            response=$(curl -s -w "\n%{http_code}" \
              --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
              --header "Content-Type: application/vnd.api+json" \
              --request POST \
              "$url")
          else
            response=$(curl -s -w "\n%{http_code}" \
              --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
              --header "Content-Type: application/vnd.api+json" \
              "$url")
          fi
          
          body=$(echo "$response" | head -n -1)
          http_code=$(echo "$response" | tail -n 1)
          
          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            if validate_json_response "$body" "$url"; then
              echo "$body"
              return 0
            fi
          fi
          
          echo "WARNING: API call failed (attempt $attempt/$max_attempts) - HTTP $http_code"
          if [ "$http_code" -eq 429 ]; then
            echo "Rate limit hit, waiting longer..."
            sleep $((RETRY_DELAY * 2))
          elif [ "$http_code" -ge 500 ]; then
            echo "Server error, retrying..."
            sleep $RETRY_DELAY
          else
            echo "Client error, aborting retries"
            break
          fi
          
          attempt=$((attempt + 1))
        done
        
        echo "ERROR: API call failed after $max_attempts attempts"
        echo "Final response: $body"
        return 1
      }
    - |
      api_call_apply_trigger() {
        local url="$1"
        local response
        local body
        local http_code
        
        response=$(curl -s -w "\n%{http_code}" \
          --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          "$url")
        
        body=$(echo "$response" | head -n -1)
        http_code=$(echo "$response" | tail -n 1)
        
        if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
          echo "$body"
          return 0
        elif [ "$http_code" -eq 409 ]; then
          echo "$body"
          return 2
        else
          echo "ERROR: API call failed - HTTP $http_code"
          echo "Response: $body"
          return 1
        fi
      }
  script:
    - set -e
    - |
      echo "Retrieving workspace information..."
      workspace_response=$(api_call_with_retry "${TF_CLOUD_API}/organizations/${TF_CLOUD_ORG}/workspaces?filter%5Bname%5D=${TF_WORKSPACE}")
      if [ $? -ne 0 ]; then
        echo "ERROR: Failed to retrieve workspace"
        exit 1
      fi
      
      workspace_count=$(echo "$workspace_response" | jq '.data | length')
      if [ "$workspace_count" -eq 0 ]; then
        echo "ERROR: Workspace '$TF_WORKSPACE' not found in organization '$TF_CLOUD_ORG'"
        exit 1
      fi
      
      WORKSPACE_ID=$(echo "$workspace_response" | jq -r '.data[0].id')
      if [ "$WORKSPACE_ID" = "null" ] || [ -z "$WORKSPACE_ID" ]; then
        echo "ERROR: Could not extract workspace ID"
        exit 1
      fi
      
      echo "Workspace ID: $WORKSPACE_ID"

    - |
      echo "Searching for GitLab CI triggered run..."
      pipeline_start_time=$(date -u -d '10 minutes ago' '+%Y-%m-%dT%H:%M:%S.%3NZ')
      echo "Looking for runs created after: $pipeline_start_time"
      
      RUN_ID=""
      attempts=0
      max_search_attempts=20
      
      while [ -z "$RUN_ID" ] && [ $attempts -lt $max_search_attempts ]; do
        echo "Search attempt $((attempts + 1))/$max_search_attempts"
        
        runs_response=$(api_call_with_retry "${TF_CLOUD_API}/organizations/${TF_CLOUD_ORG}/runs?filter%5Bworkspace%5D%5Bname%5D=${TF_WORKSPACE}&page%5Bsize%5D=50")
        if [ $? -ne 0 ]; then
          echo "WARNING: Failed to retrieve runs, retrying..."
          sleep 15
          attempts=$((attempts + 1))
          continue
        fi
        
        run_data=$(echo "$runs_response" | jq --arg start_time "$pipeline_start_time" '
          .data[] | 
          select(.attributes.message | test("Triggered by GitLab CI"))
        ' | jq -s '.[0]')
        
        if [ "$run_data" != "null" ] && [ -n "$run_data