runner-controler-start:
  stage: runner-prepare
  # Run in jobs in all runners simultaneously
  parallel: 2
  tags:
    - runner1
    - runner2
  when: manual
  allow_failure: true
  script:
    - sudo docker volume prune -af
    - sudo docker system prune -af

install-dependencies:
  stage: runner-prepare
  when: manual
  script:
    - sudo apt-get install -y curl jq tar gzip