---
include:
  - local: 'pipelines/gitlab-ci-cd/terraform/trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/apply.yml'

install-dependencies:
  stage: runner-prepare
  script:
    - apt-get install -y curl jq tar gzip

get-instance-ip-from-tf-cloud:
  stage: check-infra
  extends: .terraform-apply
  variables:
    TF_WORKSPACE: "runner2_prod"
    TF_TARGET_ADDRS: 'module.runner2'
  script:
    - echo "=== VARIABLES DIAGNOSTIC ==="
    - echo "TF_WORKSPACE = ${TF_WORKSPACE}"
    - echo "TF_TARGET_ADDRS = ${TF_TARGET_ADDRS}"
    - echo "Expected TF_WORKSPACE = runner2_prod"
    - echo "Expected TF_TARGET_ADDRS = module.runner2"
    - |
      if [ "$TF_WORKSPACE" != "runner2_prod" ]; then
        echo "ERROR: TF_WORKSPACE is wrong!"
        exit 1
      fi
    - echo "=== ALL ENV VARS ==="
    - env | grep -E "TF_|CI_" | sort
    - |
      echo "TF_WORKSPACE = ${TF_WORKSPACE}"
      WORKSPACE_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/${TF_WORKSPACE}" \
        | jq -r '.data.id')
    
    - |
      STATE_VERSION_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/current-state-version" \
        | jq -r '.data.id')
    
    - |
      INSTANCE_PUBLIC_IP=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
        | jq -r '.data[] | select(.attributes.name == "runner2_pub_ip") | .attributes.value')
    
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$INSTANCE_PUBLIC_IP" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_RUNNER2_IP" \
        > /dev/null 2>&1