---
include:
  - local: 'pipelines/gitlab-ci-cd/terraform/trigger-run.yml'
  - local: 'pipelines/gitlab-ci-cd/terraform/apply.yml'

#### NOT WORKING.... VERIFY LATER ####
before_script:
  - unset TF_WORKSPACE TF_TARGET_ADDRS
  - export TF_WORKSPACE="runner2_prod"
  - export TF_TARGET_ADDRS="module.runner2"

trigger-terraform-run:
  stage: tf-run
  extends:
    - .trigger-terraform-run

terraform-apply:
  stage: tf-apply
  extends: .terraform-apply
  needs:
    - trigger-terraform-run

install-dependencies:
  stage: runner-prepare
  script:
    - apt-get install -y curl jq tar gzip


get-instance-ip-from-tf-cloud:
  stage: check-infra
  variables:
    TF_WORKSPACE: "runner2_prod"
  script:
    - |
      WORKSPACE_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_WORKSPACE" \
        | jq -r '.data.id')
    
    - |
      STATE_VERSION_ID=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/current-state-version" \
        | jq -r '.data.id')
    
    - |
      INSTANCE_PUBLIC_IP=$(curl -s \
        --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
        --header "Content-Type: application/vnd.api+json" \
        "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
        | jq -r '.data[] | select(.attributes.name == "runner2_pub_ip") | .attributes.value')
    
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --request PUT \
        --form "value=$INSTANCE_PUBLIC_IP" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/variables/PROD_RUNNER2_IP" \
        > /dev/null 2>&1

#test